'use strict';

const { execSync } = require('child_process');
const fs = require('fs');
const os = require('os');
const path = require('path');
const brew = require('./brew.cjs');
const { adminOsascript } = require('./admin.cjs');

const SUDOERS_PATH = '/etc/sudoers.d/wpdevpilot';
// Pre-rename path. Its rules are still live sudo grants, so install/uninstall
// clear it in the same privileged step rather than leaving a stray NOPASSWD
// file behind that the app no longer knows about.
const LEGACY_SUDOERS_PATH = '/etc/sudoers.d/wpherd';
const MARKER = '# WPDevPilot sudoers';

function isConfigured() {
  try {
    if (!fs.existsSync(SUDOERS_PATH)) return false;
    // The file is installed root-owned with mode 0440, so the Electron app
    // (running as a non-root user, typically not in the `wheel` group) usually
    // cannot read its contents. An EACCES/EPERM here means the file exists and
    // is correctly locked down — i.e. configured. Only a successful read that's
    // missing our marker means some other file is squatting the path.
    try {
      const content = fs.readFileSync(SUDOERS_PATH, 'utf8');
      return content.includes(MARKER);
    } catch (err) {
      if (err.code === 'EACCES' || err.code === 'EPERM') return true;
      throw err;
    }
  } catch {
    return false;
  }
}

function generateContent() {
  const prefix = brew.getBrewPrefix() || '/opt/homebrew';
  const brewBin = `${prefix}/bin/brew`;

  // Grant passwordless sudo for brew services (start/stop/restart any formula).
  // Also covers Intel Macs — if both prefixes exist the rules are harmless.
  const lines = [
    MARKER,
    '# Generated by WPDevPilot. Remove with: sudo rm /etc/sudoers.d/wpdevpilot',
    '',
    'Defaults!WPDEVPILOT_BREW !requiretty',
    '',
    `Cmnd_Alias WPDEVPILOT_BREW = \\`,
    `    ${brewBin} services start *, \\`,
    `    ${brewBin} services stop *, \\`,
    `    ${brewBin} services restart *`,
    '',
    '%admin ALL=(ALL) NOPASSWD: WPDEVPILOT_BREW',
    '',
  ];

  // Intel fallback (no-op if same path)
  if (prefix !== '/usr/local') {
    lines.push(
      `Cmnd_Alias WPDEVPILOT_BREW_INTEL = \\`,
      `    /usr/local/bin/brew services start *, \\`,
      `    /usr/local/bin/brew services stop *, \\`,
      `    /usr/local/bin/brew services restart *`,
      '',
      '%admin ALL=(ALL) NOPASSWD: WPDEVPILOT_BREW_INTEL',
      ''
    );
  }

  return lines.join('\n');
}

function install() {
  const content = generateContent();

  // Write to a temp file (no privileges needed), then copy it into place with
  // a single admin-privileges shell invocation — avoids multi-line quoting hell.
  const tmpFile = path.join(os.tmpdir(), 'wpdevpilot-sudoers');
  fs.writeFileSync(tmpFile, content, 'utf8');

  const shellCmd = [
    `cp '${tmpFile}' '${SUDOERS_PATH}'`,
    `chmod 440 '${SUDOERS_PATH}'`,
    // Validate before leaving it in place — sudoers syntax errors lock you out.
    `visudo -cf '${SUDOERS_PATH}' || rm -f '${SUDOERS_PATH}'`,
    `rm -f '${LEGACY_SUDOERS_PATH}'`,
  ].join(' && ');

  const reason =
    'WPDevPilot wants to set up passwordless permissions so it will not ask for your ' +
    'password every time a service starts or stops.';

  try {
    execSync(adminOsascript(shellCmd, reason), {
      stdio: ['ignore', 'pipe', 'pipe'],
    });
  } finally {
    try {
      fs.rmSync(tmpFile, { force: true });
    } catch {}
  }

  if (!isConfigured()) {
    throw new Error(
      'Sudoers file was not written — visudo may have rejected the syntax.'
    );
  }
}

function uninstall() {
  if (!fs.existsSync(SUDOERS_PATH) && !fs.existsSync(LEGACY_SUDOERS_PATH)) return;
  const reason = 'WPDevPilot wants to remove its passwordless permissions.';
  execSync(adminOsascript(`rm -f '${SUDOERS_PATH}' '${LEGACY_SUDOERS_PATH}'`, reason), {
    stdio: ['ignore', 'pipe', 'pipe'],
  });
}

module.exports = {
  isConfigured,
  install,
  uninstall,
  SUDOERS_PATH,
  LEGACY_SUDOERS_PATH,
};
