'use strict';

const { execSync } = require('child_process');
const fs = require('fs');
const os = require('os');
const path = require('path');
const brew = require('./brew.cjs');

const SUDOERS_PATH = '/etc/sudoers.d/wpherd';
const MARKER = '# WPHerd sudoers';

function isConfigured() {
  try {
    if (!fs.existsSync(SUDOERS_PATH)) return false;
    const content = fs.readFileSync(SUDOERS_PATH, 'utf8');
    return content.includes(MARKER);
  } catch {
    return false;
  }
}

function generateContent() {
  const prefix = brew.getBrewPrefix() || '/opt/homebrew';
  const brewBin = `${prefix}/bin/brew`;

  // Grant passwordless sudo for brew services (start/stop/restart any formula).
  // Also covers Intel Macs — if both prefixes exist the rules are harmless.
  const lines = [
    MARKER,
    '# Generated by WPHerd. Remove with: sudo rm /etc/sudoers.d/wpherd',
    '',
    'Defaults!WPHERD_BREW !requiretty',
    '',
    `Cmnd_Alias WPHERD_BREW = \\`,
    `    ${brewBin} services start *, \\`,
    `    ${brewBin} services stop *, \\`,
    `    ${brewBin} services restart *`,
    '',
    '%admin ALL=(ALL) NOPASSWD: WPHERD_BREW',
    '',
  ];

  // Intel fallback (no-op if same path)
  if (prefix !== '/usr/local') {
    lines.push(
      `Cmnd_Alias WPHERD_BREW_INTEL = \\`,
      `    /usr/local/bin/brew services start *, \\`,
      `    /usr/local/bin/brew services stop *, \\`,
      `    /usr/local/bin/brew services restart *`,
      '',
      '%admin ALL=(ALL) NOPASSWD: WPHERD_BREW_INTEL',
      ''
    );
  }

  return lines.join('\n');
}

function install() {
  const content = generateContent();

  // Write to a temp file (no privileges needed), then copy it into place with
  // a single admin-privileges shell invocation — avoids multi-line quoting hell.
  const tmpFile = path.join(os.tmpdir(), 'wpherd-sudoers');
  fs.writeFileSync(tmpFile, content, 'utf8');

  const shellCmd = [
    `cp '${tmpFile}' '${SUDOERS_PATH}'`,
    `chmod 440 '${SUDOERS_PATH}'`,
    // Validate before leaving it in place — sudoers syntax errors lock you out.
    `visudo -cf '${SUDOERS_PATH}' || rm -f '${SUDOERS_PATH}'`,
  ].join(' && ');

  const appleScript = `do shell script "${shellCmd.replace(/"/g, '\\"')}" with administrator privileges`;

  try {
    execSync(`osascript -e '${appleScript.replace(/'/g, "'\\''")}'`, {
      stdio: ['ignore', 'pipe', 'pipe'],
    });
  } finally {
    try {
      fs.rmSync(tmpFile, { force: true });
    } catch {}
  }

  if (!isConfigured()) {
    throw new Error(
      'Sudoers file was not written — visudo may have rejected the syntax.'
    );
  }
}

function uninstall() {
  if (!fs.existsSync(SUDOERS_PATH)) return;
  const appleScript = `do shell script "rm -f '${SUDOERS_PATH}'" with administrator privileges`;
  execSync(`osascript -e '${appleScript.replace(/'/g, "'\\''")}'`, {
    stdio: ['ignore', 'pipe', 'pipe'],
  });
}

module.exports = { isConfigured, install, uninstall, SUDOERS_PATH };
